name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    # This allows the `GITHUB_TOKEN` to push packages
    # See: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

    # permissions:
    #   contents: read
    #   packages: write

    steps:
      - uses: actions/checkout@v6

      # https://github.com/actions/checkout/issues/290
      - name: Fix tags
        run: |
          git fetch --tags --force

      - name: Install nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(nix develop --command pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm
        uses: actions/cache@v5
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          nix develop --command pnpm install

      - name: Build all
        run: |
          nix develop --command ./.ci/all-ci build $(git describe)

      - name: Deploy all
        run: |
          nix develop --command ./.ci/all-ci deploy
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
